export const allServices = [
  {
    id: 1,
    title: "Solar",
    description:
      "Harness the power of the sun with our advanced solar solutions. Reduce energy costs, lower your carbon footprint, and enjoy sustainable energy tailored to your needs.",
    image: "/assets/images/solar-cell.png",
    inputs: [
      {
        question: "How much is your currency bill?",
        options: [
          "50$",
          "100$",
          "200$",
          "300$",
          "400$",
          "500$",
          "600$",
          "700$",
          "800$",
          "More than 900$",
        ],
      },
      {
        question: "How much sun hits your roof?",
        options: ["Full sun", "Partially shaded", "Mostly shaded", "Not sure"],
      },
      {
        question: "Who is your energy provider?",
        options: [
          "Unsure/Not Listed",
          "Alabama Power",
          "Alameda Municipal Power",
          "Alaska Villages Electric Cooperative",
          "Allegheny Power",
          "Alliant Energy",
          "Ambit Enery",
          "Anaheim Public Utilities",
          "Appalachain Power",
          "Arizona Public Service",
          "Ashland Electric",
          "Atlantic City Electric",
          "Austin Energy",
          "Avista Utilities",
          "Azusa Light & Water",
          "American Electric Power",
          "Ameren",
          "APS",
          "Atlantic City Electric",
          "Austin Energy",
          "Avista",
          "Baltimore Gas & Electric",
          "Bangor Hydro Electric",
          "Basin Electric Power Cooperative",
          "Batavia Municipal Electric",
          "Bear Valley Electric",
          "Beauregard Electric CO-OP",
          "Benton PUD",
          "Berea Municipal Utilities",
          "Berkeley Electric Cooperative",
          "Berkshire Company",
          "Big Rivers Electric Corporation",
          "Black Hills Energy",
          "Black Hills Power",
          "Blue Grass Energy",
          "Blue Ridae Eleatical Membershio Corp",
          "Borough of Ellwood City",
          "Bounce Energy",
          "Braintree Electric Light Department",
          "Brigham City Public Power",
          "Brunswick EMC",
          "Bryan Texas Utilities",
          "Burbank Water & Power",
          "Caddo Electric Cooperative",
          "California Public Utilities Commission",
          "Calpine",
          "Canby Electric",
          "Carteret-Craven Electric Cooperative",
          "CenterPoint Energy",
          "Central Electric Power Cooperative",
          "Central Hudson Gas & Electric",
          "Central Maine Power",
          "Central Montana Electric Power Cooperative",
          "Central Vermont Public Service",
          "CH Energy Group",
          "Champion Energy Services",
          "Chariton Valley Electric Cooperative",
          "Chelan County Public Utility District",
          "Cherokee Electric Cooperative",
          "Cheyenne Light Fuel & Power",
          "Choptank Electric Cooperative",
          "Chugach Electric Association",
          "Cincinnati Bell Energy",
          "Cirro Energy",
          "Citizens Choice Energy Jamestown BPU",
          "Citizens Electric of Lewisburg",
          "Citizens Utilities Board",
          "City & County of San Francisco",
          "City of Dover Electric Department",
          "City of Milford Electric Department",
          "City of Palo Alto Utilities",
          "City of Rock Hill",
          "City of Safford Electric Department",
          "City of Tallahassee Utilities",
          "City of Vero Beach",
          "City Utilities of Springfield",
          "Claverack REC",
          "Clay Electric Co-op",
          "Clearwater Power",
          "CLECO",
          "Cleveland Electric Illuminating Company",
          "Coast Electric",
          "College Station Utilities",
          "Colorado Springs Utilities",
          "Colton Public Utilities Glendale Public Service Department",
          "Columbia REA",
          "Columbia River Public Utility District",
          "ComEd Electric Company",
          "Connecticut Light & Power",
          "Connecticut Natural Gas",
          "Consolidated Edison Company of New York (Con Edison)",
          "Consolidated Electric Cooperative",
          "Consumers Energy",
          "Copper Valley Electric Association",
          "Coserv Electric",
          "Coweta Fayette EMC",
          "CPS Energy",
          "Dairyland Power Co-op",
          "Danville Utilities",
          "Dayton Power & Light",
          "Delaware Electric Cooperative",
          "Delmarva Power",
          "DEMCO",
          "Denton Municipal Electric",
          "Direct Energy",
          "Dominion Virginia Power",
          "Douglas County Public Utility District dPi Energy",
          "DTE Energy (Detroit Edison)",
          "Duke Energy",
          "Duke Energy Indiana",
          "Duke Energy Kentucky",
          "Duke Energy NC",
          "Duke Energy Ohio",
          "Duke Energy SC",
          "Duncan Valley Electric Cooperative",
          "Duquesne Light",
          "East River Electric Cooperative",
          "East River Electric Power Co-op",
          "Eau Claire Energy Cooperative",
          "El Paso Electric",
          "Electric Database Publishing",
          "Electric Power Board",
          "Electrical District No. 2",
          "ElectriCities",
          "Emerald PUD",
          "Empire District Electric Company",
          "Entergy",
          "Entrust Energy",
          "Eugene Water & Electric Board",
          "Everything Energy",
          "Excel Energy",
          "Farmers Electrical Cooperative",
          "Farmington Electric Utility System",
          "First Electric Cooperative",
          "First Texas Energy Corporation",
          "FirstEnergy",
          "Fleming-Mason Energy Cooperative",
          "Flint Energies",
          "Florida Municipal Power Agency",
          "Florida Power & Light",
          "Florida Public Utility Company Palm Beach",
          "Gainesville Regional Utilities",
          "Garland Power and Light",
          "Georgetown Utility Services (GUS)",
          "Georgia EMC",
          "Georgia Power",
          "Gexa Energy",
          "Golden Valley Electric Association",
          "Granite State Electric",
          "Grant County Public Utility District",
          "Great River Energy",
          "Green Island Power Authority",
          "Green Mountain Energy",
          "Green Mountain Power",
          "Gridley Municipal Utilities",
          "Guadalupe Valley Electric Cooperative",
          "Gulf Power",
          "GVEC",
          "Halifax Electric Membership",
          "Hawaiian Electric Company (HECO)",
          "Hawaiian Electric Industries",
          "Healdsburg Municipal Electric Department",
          "Henderson Municipal Power and Light",
          "High Plains Power",
          "High West Energy",
          "Highline Electric Association",
          "Holden Municipal Light Department",
          "Holland Board of Public Works",
          "Holy Cross Energy Company",
          "Howard Electric Cooperative",
          "Hutchinson Utilities Commission",
          "Hyrum City Power & Light",
          "IDACORP",
          "Idaho Power",
          "Imperial Irrigation District",
          "Independence Power and Light",
          "Indianapolis Power & Light",
          "Intermountain Power Agency",
          "Intermountain Rural Electric Association",
          "International Electric Power (IEP)",
          "Interstate Power and Light Company",
          "ITC Midwest",
          "Jackson",
          "JEA",
          "Jersey Central Power and Light Company",
          "Jones-Onslow EMC",
          "Just Energy",
          "Kansas City Board of Public Utilities",
          "Kansas City Power & Light",
          "Kauai Island Utility Cooperative (KIUC)",
          "Kaysville City",
          "Kenergy Corp",
          "Kentucky Utilities",
          "Kingsport Power (Appalachian Power)",
          "Kissimmee Utility Authority",
          "Klickitat Public Utility District",
          "Knoxville Utilities Board",
          "Kodiak Electric Association",
          "L&O Power Co-op",
          "La Plata Electric Association",
          "Lafayette Utilities System",
          "Lake Country Power",
          "Lake Worth Utilities",
          "Lakeland Electric",
          "Lamar Light and Power",
          "Lansing Board of Water & Light",
          "LCEC",
          "Lenoir City Utilities Board",
          "Little River Electric Co-Op",
          "Lodi Electric Utility",
          "Long Island Power Authority (LIPA)",
          "Lorain Medina Rural Electric Cooperative",
          "Los Angeles Department of Water and Power",
          "Louisville Gas & Electric",
          "Lower Colorado River Authority",
          "Lower Valley Energy",
          "Lumbee River EMC",
          "Luminant",
          "Madison Gas and Electric",
          "Magic Valley",
          "Magnolia Electric",
          "Mansfield Municipal Electric",
          "Marblehead Electric Light Department",
          "Marshall Municipal Utilities",
          "Mason County Public Utility District 3",
          "Massachusetts Electric",
          "Massachusetts Municipal Wholesale Electric Company (MMWEC)",
          "Massena Electric Department",
          "Maui Electric Company",
          "MDU",
          "Memphis Light Gas and Water",
          "Met-Ed",
          "MidAmerican Energy",
          "Midwest Energy",
          "Minnesota Power",
          "Minnkota Power Cooperative",
          "Mississippi Power Company",
          "Missouri River Energy Services",
          "Modesto Irrigation District",
          "Mojave Electric Cooperative",
          "Montana Electric Cooperatives' Association",
          "Montana-Dakota Utilities",
          "Mountain Utilities",
          "Municipal Light & Power",
          "Nantucket Electric",
          "Narragansett Electric",
          "Nashville Electric Service",
          "National Grid",
          "Navopache Electric Cooperative",
          "Nebraska Public Power District",
          "Nevada Power",
          "New York Power Authority (NYPA)",
          "New York State Electric & Gas (NYSEG)",
          "New-Mac Electric",
          "Norris Electric Cooperative",
          "North Carolina Electric Membership Corp.",
          "North Little Rock Electric",
          "Northeast Utilities",
          "Northern Indiana Public Service Company",
          "Northern Neck Electric Cooperative",
          "Northwestern Energy",
          "NOVEC",
          "NRG Energy",
          "NSTAR",
          "NV Energy",
          "Ocala Electric",
          "Ohio Edison",
          "Oklahoma Gas & Electric",
          "Omaha Public Power District",
          "Oncor Electric (Formerly TXU)",
          "Orange & Rockland",
          "Orlando Utilities Commission",
          "Otter Tail Power Company",
          "Overton Power District No 5",
          "Owensboro Municipal Utilities",
          "Pacific Gas & Electric",
          "PacifiCorp",
          "PacifiCorp (Pacific Power)",
          "PacifiCorp (Rocky Mountain Power)",
          "Pasadena Water & Power",
          "Peabody Municipal Light Plant",
          "PECO",
          "Pedernales Electric Cooperative",
          "Penelec",
          "Penn Power",
          "People",
          "PEPCO",
          "Pike County Light & Power Company",
          "Portland General Electric",
          "Potomoc Edison (FirstEnergy)",
          "PowerSouth Energy Cooperative",
          "PPL",
          "Progress Energy Carolinas",
          "Progress Energy Florida",
          "Public Service Company of New Mexico Public Service Company of Oklahoma",
          "Public Service Electric and Gas Company (PSE&G)",
          "Public Service of NH",
          "Puget Sound Energy",
          "PWC Fayetteville",
          "Randolph Electric Membership Corp",
          "Rappahannock Electric Cooperative",
          "Redding Electric Utility (REU)",
          "Reliant Energy",
          "River Falls Municipal Utility",
          "Riverside Public Utilities",
          "Rochester Gas & Electric",
          "Rochester Public Utilities",
          "Rural Valley Electric Co.",
          "Rushmore Electric Cooperative",
          "Sacramento Municipal Utility District",
          "Salem Electric",
          "Salt River Electric",
          "Salt River Project",
          "Sam Houston Electric",
          "San Diego Gas & Electric",
          "Santee Cooper",
          "Sawnee EMC",
          "Seattle City Light",
          "SELCO",
          "Shenandoah Valley Electric Cooperative",
          "Sierra Pacific Power",
          "Sierra-Pacific Power",
          "Silicon Valley Power",
          "SLECMO",
          "Snohomish County Public Utility District (PUD)",
          "Source Power and Gas",
          "South Carolina Electric & Gas Company",
          "South Central Power Company",
          "Southern California Edison",
          "Southern California Public Power Authority",
          "Southern Maryland Electric Cooperative",
          "Southern Rivers Energy",
          "Southwest Mississippi Electric Power Association",
          "Southwestern Electric Power Company (SWEPCO)",
          "Springfield City Water Light & Power",
          "Star Tex Power",
          "Sterling Municipal Light Department",
          "Stream Energy",
          "Sulphur Springs Valley Electric Cooperative",
          "Summer Energy",
          "Superior Plus Utility",
          "Surprise Valley Power",
          "Sussex Rural Electric Cooperative",
          "SWEPCO",
          "Tacoma Power",
          "Tara Energy",
          "TECO",
          "Tennessee Jackson Energy Authority",
          "Tennessee Valley Authority",
          "Texas Electric Service Company",
          "Tideland EMC",
          "Tillamook PUD",
          "Toledo Edison",
          "Town of Vienna",
          "Tri Eagle Energy",
          "Trico Electric Cooperative",
          "Tri-County Electric",
          "Trinity PUD",
          "Trinity Valley Electric Cooperative",
          "Tucson Electric Power",
          "Turlock Irrigation District (TID)",
          "UGI Utilities",
          "UniSource Energy Services",
          "United Cooperative Services",
          "United Illuminating",
          "United Power Inc",
          "Unitil Corporation",
          "Upper Missouri G&T Cooperative",
          "Upper Peninsula Power Company",
          "Valley Electric Association",
          "Vernon Light & Power",
          "Vineland Municipal Electric Utility",
          "Wake Electric",
          "Wakefield Municipal Gas and Light Department",
          "Wallingford Electric",
          "Wasco Electric",
          "Washington - St. Tammany Electric Cooperative",
          "We Energies",
          "Weakley County Municipal Electric System",
          "Wellsboro Electric Company",
          "West Oregon Electric Cooperative",
          "Westar Energy",
          "Western Massachusetts Electric",
          "Wheeling Electric Power (AEP Ohio)",
          "Wilson Energy",
          "Wiregrass Electric Cooperative",
          "Wisconsin Power and Light Company",
          "Wisconsin Public Service Corporation",
          "Withlacoochee River Electric Cooperative",
          "WTU Retail Energy",
          "Wyandotte Municipal Services",
          "XOOM Energy",
          "Xcel Energy",
          "Other",
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Windows",
    description:
      "Enhance your home’s and offices beauty and efficiency with our premium window services. From installations to replacements, we provide energy-saving, stylish, and durable options.",
    image: "/assets/images/windows.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["Install", "Repair"],
      },
      {
        question: "How many windows are involved?",
        options: [
          "1 window",
          "2 windows",
          "3-5 windows",
          "6-9 windows",
          "10+ windows",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
      {
        question: "What is the material of your windows",
        options: ["Vinyl", "Wood", "Aluminium", "Brick", "Stone", "Metal"],
      },
    ],
  },
  {
    id: 3,
    title: "Roofing",
    description:
      "Protect your home with our reliable roofing solutions. Whether you need new roof, repairs, or maintenance, we ensure durability, safety, and top-notch craftsmanship.",
    image: "/assets/images/roof.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New", "Repair", "Replace"],
      },
      {
        question: "What type of material do you need",
        options: [
          "Ashphalt Shingle",
          "Cedar Shake",
          "Metal",
          "Natural Slate",
          "Tar",
          "Other",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 4,
    title: "HVAC",
    description:
      "Stay comfortable year-round with our HVAC services. From installation to maintenance, we optimize your heating and cooling systems for peak efficiency.",
    image: "/assets/images/air.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New", "Repair", "Replace"],
      },
      {
        question: "What type of HVAC do you need",
        options: [
          "Air Ducts Repair & Replace",
          "Boiler & Radiators-New install",
          "Central air cleaning & maintinance",
          "Central air-New install",
          "Central air-Repair",
          "Commercial Cooling",
          "Commercial Heat-New install",
          "Commercial Heat-Repair",
          "Ductless Air Conditioning",
          "Furnaces-New install",
          "Furnaces-Repair",
          "Gas Heat-New install",
          "Gas Heat-Repair",
          "Geothermal Systems",
          "Heating-New install",
          "Heating-Repair",
          "Heat Pumps-New install",
          "Heat Pumps-Repair",
          "Oil Heat-New install",
          "Oil Heat-Repair",
          "Radiant Floor system",
          "Thermostats",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 5,
    title: "Painting",
    description:
      "Transform your space with our expert painting services. We deliver flawless finishes and vibrant colors that breathe life into your home or business.",
    image: "/assets/images/painting.png",
    inputs: [
      {
        question: "Type of painting needed",
        options: [
          "Exterior painting - Trim/Shutters",
          "Exterior painting - Whole House",
          "Paint or Stain - Deck/Fence/Porch",
          "Interior Painting 1-2 Rooms",
          "Interior Painting 3+ Rooms",
          "Wallpaper Hanging/Removal",
          "Speciality- Faux Finishes",
          "Speciality - Textures",
          "Commercial",
          "Paint Removal or Stripping",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 6,
    title: "Plumbing",
    description:
      "Solve your plumbing problems with our fast and efficient services. From leaky faucets to major installations, we ensure everything flows smoothly.",
    image: "/assets/images/water-supply.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New", "Repair", "Replace"],
      },
      {
        question: "Type of plumbing needed?",
        options: [
          "Basement Drainage Channel",
          "Bathtubs",
          "Commercial Industrial Plumbing",
          "Faucets Fixtures Pipes",
          "Gas pipes",
          "General Repair",
          "Leak Detection And Repair",
          "Remodeling and construction",
          "Sewer and Drain",
          "Other",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 7,
    title: "Gutters",
    description:
      "Keep your home safe from water damage with our seamless gutter solutions. We offer installation, repair, and cleaning services for optimal drainage.",
    image: "/assets/images/gutter.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New", "Repair", "Replace"],
      },
      {
        question: "Type of product needed",
        options: ["Galvanized", "Seamless Metal", "PVC", "Other"],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 8,
    title: "HomeSecurity",
    description:
      "Secure your peace of mind with our advanced home security systems. Protect your loved ones with cutting-edge technology and professional installation.",
    image: "/assets/images/insurance.png",
    inputs: [
      {
        question: "Type of service needed",
        options: [
          "Equipment Only",
          "New System Installation",
          "Reactivating The Existing System",
        ],
      },
    ],
  },
  {
    id: 9,
    title: "Kitchen",
    description:
      "Create your dream kitchen with our expert remodeling and installation services. We blend functionality and style to make your culinary space extraordinary.",
    image: "/assets/images/kitchen.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New Kitchen", "Repair Kitchen", "Replace Kitchen"],
      },
      {
        question: "Type of remodeling needed?",
        options: [
          "Appliances",
          "Cabinets",
          "Cabinet Repair",
          "Counter Tops or Sinks",
          "Floor Plan",
          "Flooring",
          "Full Kitchen",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 10,
    title: "Siding",
    description:
      "Enhance your home’s curb appeal and durability with our top-quality siding services. Choose from a variety of styles and materials for lasting beauty.",
    image: "/assets/images/siding.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New", "Repair", "Replace"],
      },
      {
        question: "What type of project",
        options: [
          "Aluminium - Install/Replace",
          "Aluminium Repair",
          "BrickFace Install/Replace",
          "BrickFace Repair",
          "Composite Wood - Install/Replace",
          " Composite Wood - Repair",
          "StoneFace- Install/Replace",
          "StoneFace- Repair",
          "Stucco- Install/Replace",
          "Stucco - Repair",
          "Vinyl- Install/Replace",
          "Vinyl-Repair",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 11,
    title: "Bathroom",
    description:
      "Revitalize your bathroom with our modern renovation solutions. From luxurious upgrades to practical fixes, we craft spaces that blend comfort and elegance.",
    image: "/assets/images/public-toilet.png",
    inputs: [
      {
        question: "What is the nature of your project?",
        options: ["New Bath Install", "Bathroom Remodel"],
      },
      {
        question: "Type of remodeling needed",
        options: [
          "BathTub Install",
          "BathTub Linear Install",
          "Cabinets",
          "Counter Tops",
          "Full Remodel",
          "General Remodeling",
          "New Florring",
          "Shower Install",
          "Sink Install",
          "Toilet Install",
          "Walk-In Tub Install",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 12,
    title: "Fencing",
    description:
      "Define your property with our custom fencing solutions. We provide durable, stylish, and secure options to fit your needs and style.",
    image: "/assets/images/fence.png",
    inputs: [
      {
        question: "Type of fencing project?",
        options: [
          "Wood Fence Install/Replace",
          "Wood Fence Repair",
          "Vinyl or PVC Fence Install/Replace",
          "Vinyl or PVC Fence Repair",
          "Chain Link Fence Install/Replace",
          "Chain Link Fence Repair",
          "Wrought Iron Fence Install/Relace",
          "Wrought Iron Fence Repair",
          "Aluminium Or Steel Fence Install/Replace",
          "Aluminium Or Steel Fence Repair",
          "Barbed Wired Fence Install/Replace",
          "Barbed Wired Fence Repair",
          "Electric Pet Fence Install/Replace",
          "Electric Pet Fence Repair",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 13,
    title: "Flooring",
    description:
      "Upgrade your home with our premium flooring services. From hardwood to tiles, we offer elegant, durable, and cost-effective solutions for every space.",
    image: "/assets/images/tiles.png",
    inputs: [
      {
        question: "Floor Type?",
        options: [
          "Carpet - install",
          "Carpet- Repair or Refasten",
          "Epoxy Flooring",
          "Hardwood Floor- Install",
          "Laminate Floor- Install",
          "Laminate Floor- Repair",
          "Tile Floor- Install/Repare",
          "Vinyl Or Linoleum Floor-Install",
          "Vinyl Or Linoleum Floor - Repair",
          "Wood Floor - Refinishing",
          "Wood Floor - Repair or Partially Replace",
        ],
      },
      {
        question: "Project status?",
        options: ["Ready to hire", "Planning and budgeting"],
      },
    ],
  },
  {
    id: 14,
    title: "Movers",
    description:
      "Make your move seamless with our professional moving services. we ensure safe, and stress-free relocation for homes and businesses.",
    image: "/assets/images/shipping-truck.png",
    inputs: [
      {
        question: "Current zip code",
      },
      {
        question: "Moving zip code",
      },
      {
        question: "Move size",
        options: [
          "Studio",
          "1 Bedroom",
          "2 Bedrooms",
          "3 Bedrooms",
          "4 Bedrooms",
          "Over 4 Bedrooms",
          "Partial Home",
        ],
      },
      {
        question: "When are you planning to move", 
        type: "date",
      },
    ],
  },
];
